version: '3.9'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
  pg_db:
    image: postgres:15
    container_name: pg_db
    environment:
      - POSTGRES_USER=${PG_DB_USER}
      - POSTGRES_PASSWORD=${PG_DB_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
      - POSTGRES_HOST=${PG_DB_HOST}
      - POSTGRES_PORT=${PG_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_db:/var/lib/postgresql/data/
    env_file:
      - .env
volumes:
  pg_db: