name: Python CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-html mypy autopep8 black isort

      # Run auto-fix tools
      - name: Auto-fix with Black, Autopep8, and isort
        run: |
          black .
          autopep8 --in-place --recursive .
          isort .

      # Run the linters and generate an HTML report
      - name: Check and Upload Lint Report
        if: always()  # Ensure this step runs even if the previous step fails
        run: |
          if [ -d reports/linting-report ]; then
            echo "Linting report exists, proceeding to upload."
          else
            echo "No linting report found. Creating placeholder."
            mkdir -p reports/linting-report
            echo "<html><body>No linting issues detected or linting failed to produce output.</body></html>" > reports/linting-report/index.html
          fi

      - name: Upload Lint Report
        if: always()  # Ensure this step runs even if the previous step fails
        uses: actions/upload-artifact@v3
        with:
          name: linting-report
          path: reports/linting-report

      # Type checking
      - name: Run mypy type checks
        run: |
          mypy . --ignore-missing-imports

  notify-success:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Send success message to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: '✅ CI Passed: Python linting, type-checking, and tests succeeded on Python versions 3.7, 3.8, and 3.9.'
          debug: true

  notify-failure:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: failure()

    steps:
      - name: Send failure message to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "❌ CI Failed: Issues detected in linting, type-checking, or tests for Python versions 3.7, 3.8, and 3.9."
          debug: true